version: '3.7'
services:
    app_base:
        container_name: app_base
        build:
            dockerfile: docker/app/app.dockerfile
            context: ./
        image: app_base
        restart: always
        volumes:
            - D:\Dados\Docker\app_base:c:\app_base
        ports:
            - "0.0.0.0:8000:80"
        networks:
            - default
        cpus: 4
        mem_limit: 2048M
networks:
  default:
    external:
      name: nat