path_app_root = "c:/app_base"
path_app_conf = path_app_root + '/conf'
path_app_data = path_app_root + '/data'
path_app_data_successful = path_app_data + '/successful'
path_app_data_unsuccessful = path_app_data + '/unsuccessful'
path_app_log = path_app_root + '/log'
path_app_model = path_app_root + '/model'
path_app_model_uploaded = path_app_root + '/model/uploaded'
path_app_model_generated = path_app_root + '/model/generated'